@startuml
!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!includeurl https://raw.githubusercontent.com/HomeMadeBots/Physical_Quantities_Interfaces/main/doc/Ambient_Air_Temperature.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/DS18B20_Ambient_Air_Temperature_Sensor/main/doc/DS18B20_Ambient_Air_Temperature_Sensor.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/One_Wire_Interfaces/main/doc/One_Wire_Protocol.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Physical_Quantities_Interfaces/main/doc/T_Ambient_Air_Temperature.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/One_Wire_Interfaces/main/doc/T_One_Wire_Device_Address.puml

Ambient_Air_Temperature <|..# "Ambient_Air_Temperature" DS18B20_Ambient_Air_Temperature_Sensor

DS18B20_Ambient_Air_Temperature_Sensor "One_Wire_Comm" #..> One_Wire_Protocol

Ambient_Air_Temperature .right.> T_Ambient_Air_Temperature : use

One_Wire_Protocol .right.> T_One_Wire_Device_Address : use

@enduml